/*
 * DIO_cfg.c
 *
 *  Created on: Feb 8, 2025
 *      Author: kerel
 */

#include "DIO_interface.h"
#include "DIO_private.h"


const DioDirection_Type config_pins[NUM_OF_PINS]=
{
		OUTPUT,	//	PA0 PIN0
		OUTPUT,	//	PA1 PIN1
		OUTPUT,	//	PA2 PIN2
		OUTPUT,	//	PA3 PIN3
OUTPUT,	//	PA4 PIN4
OUTPUT,	//	PA5 PIN5
OUTPUT,	//	PA6 PIN6
OUTPUT,	//	PA7 PIN7
OUTPUT,	//	PB0 PIN8
OUTPUT,	//	PB1 PIN9
INPUT_FLOATING,	//	PB2 PIN10
INPUT_FLOATING,	//	PB3 PIN11
INPUT_FLOATING,	//	PB4 PIN12
INPUT_FLOATING,	//	PB5 PIN13
INPUT_FLOATING,	//	PB6 PIN14
INPUT_FLOATING,	//	PB7 PIN15
INPUT_FLOATING,	//	PC0 PIN16
INPUT_FLOATING,	//	PC1 PIN17
INPUT_FLOATING,	//	PC2 PIN18
INPUT_FLOATING,	//	PC3 PIN19
INPUT_FLOATING,	//	PC4 PIN20
INPUT_FLOATING,	//	PC5 PIN21
INPUT_FLOATING,	//	PC6 PIN22
INPUT_FLOATING,	//	PC7 PIN23
OUTPUT,	//	PD0 PIN24
OUTPUT,	//	PD1 PIN25
OUTPUT,	//	PD2 PIN26
OUTPUT,	//	PD3 PIN27
INPUT_PULLUP,	//	PD4 PIN28
INPUT_PULLUP,	//	PD5 PIN29
INPUT_PULLUP,	//	PD6 PIN30
INPUT_PULLUP,	//	PD7 PIN31
};
